.\" Man Page for WMBATPPC
.\" groff -man -Tascii wmbatppc.1
.\"
.TH WMBATPPC 1 "NOVEMBER 2000" Linux "User Manuals"
.SH NAME
wmbatppc
.SH SYNOPSIS
.B wmbatppc
[\-c command]
.SH DESCRIPTION
.B wmbatppc
displays, as a WindowMaker dockapp, power management information
on new PowerBooks (aka Pismo) and iBook.
.SH OPTIONS

.TP
.I \-r time
Sets the update interval (in milliseconds), default: 100
.TP
.I \-display display
This option specifies the X server to contact; see X(1).
.TP
.I \-w
This option enables the WindowMaker/AfterStep GUI (64*64 pixmap)
.TP
.I \-x
This option enables the swallowed application GUI (24*176 pixmap)
intended for use with the GNOME Panel.

.SH BUGS
Please report any bugs you may find to:
.TP
.B titelou@free.fr 
.SH AUTHOR
Lou <titelou@free.fr>
.SH Homepage
http://titelou.free.fr/
